### ISSUE TITLE
Performance tests (read/write) Python 3.x compatibility

### ISSUE THREAD

**Issue by ds-dev** [AleksTk/varint#2]
time python3 -m varinttest.performance.write py 10000 tmp
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hp/workspace/2016DSDEV_VarInt/varinttest/performance/write.py", line 23, in <module>
    for i in xrange(n_elements):
NameError: name 'xrange' is not defined

**Comment by ds-dev** [comment]
Implemented read/write using implicit python calls and PyObject's inner buffer, results:

time python3 -m varinttest.performance.write py 4000000 tmp

real	0m12.884s
user	0m12.456s
sys	0m0.036s

time python3 -m varinttest.performance.write c 4000000 tmp

real	0m9.775s
user	0m9.612s
sys	0m0.052s

time python3 -m varinttest.performance.read py 4000000 tmp

real	0m8.289s
user	0m8.252s
sys	0m0.028s

 time python3 -m varinttest.performance.read c 4000000 tmp

real	0m5.525s
user	0m5.468s
sys	0m0.012s
